export const actionTypes= {
    READ_LISTING : 'READ_LISTING',
    READ_LISTING_ERROR : 'READ_LISTING_ERROR',
    LIST_ALL: 'LIST_ALL',
    LIST_ALL_ERROR: 'LIST_ALL_ERROR',
    
    INPUT_CHANGE: 'INPUT_CHANGE',
    INPUT_CHANGE_ERROR: 'INPUT_CHANGE_ERROR',
    SENDMAIL : 'SENDMAIL' ,
    SENDMAIL_ERROR : 'SENDMAIL_ERROR' ,

    READ_ACTIVE_VIEW : 'READ_ACTIVE_VIEW',
    READ_ACTIVE_MENU : 'READ_ACTIVE_MENU',
    MENU_ERROR : 'MENU_ERROR'

}

