export const actionTypes= {
    LIST_PROJECTS : 'LIST_PROJECTS',
    LISTING_ERROR : 'LISTING_ERROR',
    LIST_CHANGES: 'LIST_CHANGES',
    RESET_LIST : 'RESET_LIST',
    // LIST_ALL: 'LIST_ALL',
    // LIST_ALL_ERROR: 'LIST_ALL_ERROR',
    
    INPUT_CHANGE: 'INPUT_CHANGE',
    INPUT_CHANGE_ERROR: 'INPUT_CHANGE_ERROR',
    SENDMAIL : 'SENDMAIL' ,
    SENDMAIL_ERROR : 'SENDMAIL_ERROR' ,
    RESET_INPUTS: 'RESET_INPUTS',
    RESET_ERRORS: 'RESET_ERRORS',

    CHANGE_MENU : 'CHANGE_MENU',
    READ_ACTIVE_MENU : 'READ_ACTIVE_MENU',
    MENU_ERROR : 'MENU_ERROR',
    RESET_MENU: 'RESET_MENU'

}

